version: '2'
services:

  simple-node:
    build:
      context: .
    ports:
      # expose local port 7070 and redirect it to the container's inner port 8080 (the one the server listens to)
      - 7070:8080
      # expose ports for node-inspector to be accessed remotely
      - '9090:9090'
      - '5858:5858'
    volumes:
      - .:/usr/src/app